name: rljson
description: Define and manage relational data structures in JSON with ease
version: 3.0.1
repository: https://github.com/inlavigo/rljson.git

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  gg_json_hash: ^2.0.5

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
