name: rljson
description: Define and manage relational data structures in JSON with ease
version: 3.0.3
repository: https://github.com/inlavigo/rljson.git

environment:
  sdk: ">=3.13.0 <4.0.0"

dependencies:
  gg_json_hash: ^5.2.0

dev_dependencies:
  lints: ^6.1.0
  test: ^1.31.2