name: rljson
description: Define and Manage Relational Data Structures in JSON with Ease
version: 1.0.0
repository: https://github.com/inlavigo/rljson.git

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  path: ^1.8.0
  gg_json_hash: ^1.1.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
