name: rljson
description: Define and manage relational data structures in JSON with ease
version: 3.0.3
repository: https://github.com/inlavigo/rljson.git

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  gg_json_hash: ^4.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
